spring:    
  main:
    allow-bean-definition-overriding: true
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
      username: sys as sysdba
      password: Oradoc_db1
      hikari:
          poolName: Hikari
          auto-commit: false
  jpa:
      database-platform: org.hibernate.dialect.Oracle12cDialect
      database: ORACLE
      show-sql: true
      hibernate:
        ddl-auto: update    
server:
    port: 8080